@startuml DPO

actor "Electrical Connection Technician" as technician
actor "Supervisor" as supervisor

left to right direction

rectangle "DPO" as DPO {
    usecase "Create a binding statement" as createStatement
    usecase "Filling the form in the GUI" as gui
    usecase "Prompt whether to open the GUI" as prompt
    usecase "Create more binding statements" as createStatements
    usecase "Send statement" as send
}


technician -- createStatement
createStatement ..> prompt : <<include>>
prompt <.. gui : <<extend>>

technician -- createStatements
createStatements ..> prompt : <<include>>

technician -- send
send --> supervisor

@enduml 
